# Generated by Django 4.2.3 on 2023-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_products_image2_products_image4_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_img3'),
        ),
    ]
