# Generated by Django 4.2.3 on 2023-08-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_products_image3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Series',
        ),
    ]
