# Generated by Django 4.2.3 on 2023-08-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_delete_category_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Productseries_img')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField()),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
