# Generated by Django 4.2.3 on 2023-08-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseries',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductSeries',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
