# Generated by Django 4.2.3 on 2023-08-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_subcategory_productseries_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseries',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductSeries',
        ),
    ]
