# Generated by Django 4.2.3 on 2023-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_products_image5_products_image6_products_image7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_vdo'),
        ),
    ]
