# Generated by Django 4.2.3 on 2023-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Second_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.TextField(verbose_name=6)),
            ],
        ),
    ]
