# Generated by Django 4.2.3 on 2023-08-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkout_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_address',
            name='pincode',
        ),
    ]
