# Generated by Django 4.2.3 on 2023-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_checkout_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_address',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
