# Generated by Django 4.2.3 on 2023-08-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_checkout_address_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout_address',
        ),
    ]
