# Generated by Django 4.2.3 on 2023-08-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_address',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout_address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
