# Generated by Django 4.2.3 on 2023-08-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_profile_district_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout_address',
        ),
    ]
