# Generated by Django 4.2.3 on 2023-08-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_products_video'),
        ('cart', '0012_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orders')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.products')),
            ],
        ),
    ]
