# Generated by Django 4.2.3 on 2023-10-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('on the way', 'on the way'), ('Delivered', 'Delivered'), ('cancel', 'cancel'), ('pending', 'pending')], default='pending', max_length=50, null=True),
        ),
    ]
